[mypy]
python_version = 3.12
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = False
warn_unused_ignores = True
no_implicit_optional = True
show_error_codes = True
warn_return_any = True
warn_unused_configs = True
follow_imports = skip
exclude = (migrations/|tests/|scripts/)

[mypy-extensions]
disallow_untyped_defs = True

[mypy-utils]
disallow_untyped_defs = True

[mypy-models.*]
disallow_untyped_defs = True

[mypy-log_activity]
disallow_untyped_defs = True

[mypy-email_service]
disallow_untyped_defs = True

[mypy-webhook_service]
disallow_untyped_defs = True

[mypy-push_service]
disallow_untyped_defs = True
