"""add social accounts and posts

Revision ID: 1629a0c320e3
Revises: fd52030b8fb3
Create Date: 2026-06-15 21:15:07.120142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1629a0c320e3'
down_revision = 'fd52030b8fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('page_id', sa.String(length=100), nullable=True),
    sa.Column('ig_user_id', sa.String(length=100), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.create_index('ix_social_posts_status', ['status', 'scheduled_at'], unique=False)

    op.drop_table('comparable')
    op.drop_table('tasacion')
    op.drop_table('empresa_config')
    with op.batch_alter_table('appraisal_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appraisal_versions_appraisal'))

    with op.batch_alter_table('comparables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparables_appraisal'))

    with op.batch_alter_table('portal_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_logs_portal_created'))

    with op.batch_alter_table('portal_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_publications_portal_property'))
        batch_op.drop_index(batch_op.f('ix_portal_publications_portal_rental'))

    with op.batch_alter_table('portal_queue', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('ix_portal_queue_portal_processed_created'))
        batch_op.drop_index(batch_op.f('ix_portal_queue_retry'))
        batch_op.drop_index(batch_op.f('ix_portal_queue_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portal_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_queue_retry'), ['status', 'next_retry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_queue_portal_processed_created'), ['portal_id', 'processed', 'created_at'], unique=False)
        batch_op.alter_column('retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('portal_publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_publications_portal_rental'), ['portal_id', 'rental_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_publications_portal_property'), ['portal_id', 'property_id'], unique=False)

    with op.batch_alter_table('portal_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_logs_portal_created'), ['portal_id', 'created_at'], unique=False)

    with op.batch_alter_table('comparables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparables_appraisal'), ['appraisal_id'], unique=False)

    with op.batch_alter_table('appraisal_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appraisal_versions_appraisal'), ['appraisal_id'], unique=False)

    op.create_table('empresa_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('subtitulo', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('tasador_nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('tasador_matricula', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('color_principal', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logo_secundario_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('empresa_config_pkey'))
    )
    op.create_table('tasacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('solicitante', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('telefono_solicitante', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fecha_tasacion', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('destino', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tipo_propiedad', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('barrio', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('localidad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('provincia', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('anio_construccion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('superficie_terreno', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('superficie_cubierta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dormitorios', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('banos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tiene_cochera', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('estado_conservacion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('calidad_ubicacion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tipo_cambio_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valor_m2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_estimado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_estimado_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tasacion_pkey'))
    )
    op.create_table('comparable',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tasacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('barrio', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('localidad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('moneda', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('tipo_operacion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('superficie_cubierta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('superficie_terreno', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dormitorios', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('banos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tiene_cochera', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('anio_construccion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inmobiliaria', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('url_origen', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dias_en_mercado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio_m2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ajuste_antiguedad', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ajuste_cochera', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ajuste_habitaciones', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ajuste_ubicacion', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ajuste_mantenimiento', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ajuste_comodidades', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('coeficiente', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precio_m2_ajustado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tasacion_id'], ['tasacion.id'], name=op.f('comparable_tasacion_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comparable_pkey'))
    )
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.drop_index('ix_social_posts_status')

    op.drop_table('social_posts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
