"""add management fields to portal publications

Revision ID: 1689bbab9755
Revises: 249cea0b22cc
Create Date: 2026-07-02 10:54:24.598646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1689bbab9755'
down_revision = '249cea0b22cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portal_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assigned_agent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paused_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'agents', ['assigned_agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portal_publications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('paused_at')
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('assigned_agent_id')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
