"""empty message

Revision ID: 2c8018d80912
Revises: e6f7g8h9i0j1
Create Date: 2026-05-30 21:53:47.664289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8018d80912'
down_revision = 'e6f7g8h9i0j1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_title', sa.String(length=200), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appraisal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'date', name='uq_property_view_date')
    )
    with op.batch_alter_table('property_views', schema=None) as batch_op:
        batch_op.create_index('idx_property_view_date', ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_views_property_id'), ['property_id'], unique=False)

    op.create_table('rental_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rental_id', 'date', name='uq_rental_view_date')
    )
    with op.batch_alter_table('rental_views', schema=None) as batch_op:
        batch_op.create_index('idx_rental_view_date', ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rental_views_rental_id'), ['rental_id'], unique=False)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index('idx_property_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_property_status', ['status'], unique=False)
        batch_op.create_index('idx_property_type', ['type'], unique=False)

    conn = op.get_bind()
    inspector = sa.inspect(conn)
    rentals_cols = [c['name'] for c in inspector.get_columns('rentals')]
    has_agent_id = 'agent_id' in rentals_cols

    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.alter_column('price_ars',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_index('idx_rental_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_rental_status', ['status'], unique=False)
        batch_op.create_index('idx_rental_type', ['type'], unique=False)
        if has_agent_id:
            batch_op.drop_constraint(batch_op.f('rentals_agent_id_fkey'), type_='foreignkey')
            batch_op.drop_column('agent_id')
            batch_op.drop_column('rooms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rooms', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('rentals_agent_id_fkey'), 'agents', ['agent_id'], ['id'])
        batch_op.drop_index('idx_rental_type')
        batch_op.drop_index('idx_rental_status')
        batch_op.drop_index('idx_rental_created_at')
        batch_op.alter_column('price_ars',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index('idx_property_type')
        batch_op.drop_index('idx_property_status')
        batch_op.drop_index('idx_property_created_at')

    with op.batch_alter_table('rental_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_views_rental_id'))
        batch_op.drop_index('idx_rental_view_date')

    op.drop_table('rental_views')
    with op.batch_alter_table('property_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_views_property_id'))
        batch_op.drop_index('idx_property_view_date')

    op.drop_table('property_views')
    op.drop_table('appraisal_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
