"""ml attributes

Revision ID: 4873662db133
Revises: cdc74d7367fb
Create Date: 2026-06-21 22:54:10.417506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4873662db133'
down_revision = 'cdc74d7367fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portal_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ml_listing_type', sa.String(length=30), nullable=True))

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sqm_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('parkings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('antiquity', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('floor', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('floor')
        batch_op.drop_column('antiquity')
        batch_op.drop_column('parkings')
        batch_op.drop_column('sqm_total')

    with op.batch_alter_table('portal_publications', schema=None) as batch_op:
        batch_op.drop_column('ml_listing_type')

    # ### end Alembic commands ###
