"""add appraisal management models

Revision ID: 65331456670e
Revises: 8955bf9a0f8e
Create Date: 2026-07-02 10:24:50.635410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65331456670e'
down_revision = '8955bf9a0f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appraisal_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appraisal_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appraisal_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_agent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'agents', ['assigned_agent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('priority')
        batch_op.drop_column('assigned_agent_id')

    op.drop_table('appraisal_timeline')
    op.drop_table('appraisal_files')
    op.drop_table('appraisal_comments')
    # ### end Alembic commands ###
