"""add appraisal_request_id to appraisals

Revision ID: 70061a7ae357
Revises: a9b8c7d6e5f4
Create Date: 2026-06-20 23:30:17.989563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70061a7ae357'
down_revision = 'a9b8c7d6e5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appraisal_request_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'appraisal_requests', ['appraisal_request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('appraisal_request_id')

    # ### end Alembic commands ###
