"""add sync columns to portal_publications

Revision ID: 80f2818ca382
Revises: b8c9d0e1f2a3
Create Date: 2026-06-21 21:44:06.968584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f2818ca382'
down_revision = 'b8c9d0e1f2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portal_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ml_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ml_data_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('local_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_portal_publications_ml_synced_at'), ['ml_synced_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portal_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_publications_ml_synced_at'))
        batch_op.drop_column('local_hash')
        batch_op.drop_column('ml_data_hash')
        batch_op.drop_column('ml_synced_at')

    # ### end Alembic commands ###
