"""social templates + engagement fields

Revision ID: 8955bf9a0f8e
Revises: da753abf59aa
Create Date: 2026-06-30 21:15:16.417475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8955bf9a0f8e'
down_revision = 'da753abf59aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recurring_interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('engagement_likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('engagement_comments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('engagement_shares', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('engagement_saved', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'social_templates', ['template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('engagement_saved')
        batch_op.drop_column('engagement_shares')
        batch_op.drop_column('engagement_comments')
        batch_op.drop_column('engagement_likes')
        batch_op.drop_column('recurring_interval')
        batch_op.drop_column('template_id')

    op.drop_table('social_templates')
    # ### end Alembic commands ###
