"""add comp_orientacion comp_vistas comp_nivel_piso to comparable

Revision ID: 9c49c2867939
Revises: 0a17ada6f921
Create Date: 2026-06-22 21:45:37.375057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c49c2867939'
down_revision = '0a17ada6f921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comparables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comp_orientacion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('comp_vistas', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('comp_nivel_piso', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comparables', schema=None) as batch_op:
        batch_op.drop_column('comp_nivel_piso')
        batch_op.drop_column('comp_vistas')
        batch_op.drop_column('comp_orientacion')

    # ### end Alembic commands ###
