"""add excluido to comparables

Revision ID: cdc74d7367fb
Revises: 80f2818ca382
Create Date: 2026-06-21 22:00:12.290192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc74d7367fb'
down_revision = '80f2818ca382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comparables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excluido', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comparables', schema=None) as batch_op:
        batch_op.drop_column('excluido')

    # ### end Alembic commands ###
