"""crm_full: lead_activity_tasks_visits_reminders_automation

Revision ID: da753abf59aa
Revises: 9c49c2867939
Create Date: 2026-06-22 22:33:13.535016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da753abf59aa'
down_revision = '9c49c2867939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_config', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('action_config', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_actions', sa.Integer(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_property_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('interest_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('reminder_at', sa.DateTime(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_type', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('email_subject', sa.String(length=300), nullable=True),
    sa.Column('email_to', sa.String(length=200), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('reminder_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preferred_contact_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source_detail', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pipeline_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estimated_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('conversion_probability', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lead_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loss_reason', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('budget_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('budget_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('utm_source', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('utm_medium', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('utm_campaign', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_contacted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_followup_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('leads_agent_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('leads_property_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('property_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('leads_property_id_fkey'), 'properties', ['property_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('leads_agent_id_fkey'), 'agents', ['agent_id'], ['id'])
        batch_op.drop_column('next_followup_at')
        batch_op.drop_column('last_contacted_at')
        batch_op.drop_column('utm_campaign')
        batch_op.drop_column('utm_medium')
        batch_op.drop_column('utm_source')
        batch_op.drop_column('budget_max')
        batch_op.drop_column('budget_min')
        batch_op.drop_column('loss_reason')
        batch_op.drop_column('lead_score')
        batch_op.drop_column('conversion_probability')
        batch_op.drop_column('estimated_value')
        batch_op.drop_column('pipeline_order')
        batch_op.drop_column('source_detail')
        batch_op.drop_column('preferred_contact_method')
        batch_op.drop_column('whatsapp')

    op.drop_table('lead_activities')
    op.drop_table('reminders')
    op.drop_table('visits')
    op.drop_table('tasks')
    op.drop_table('lead_property_interests')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
